"""
مُركِّب اختبارات FireEngineerAI 1.5.1

ضع هذا الملف في C:\\Projects\\FireEngineerAI ثم شغّله:

    python install_tests.py

ينشئ مجلد tests وملفات الإعداد، ويصلح خطأ is_overdue في database.py.
آمن للتشغيل أكثر من مرة: لا يكرّر الإصلاح ولا يفسد شيئًا.
"""

import base64
import os
import shutil
import sys

FILES = {
    'tests/conftest.py': (
        "IiIiCmNvbmZ0ZXN0LnB5IOKAlCDYqtmH2YrYptipINmF2LTYqtix2YPYqSDZhNin2K7Yqtio2KfYsdin2KogRmlyZUVu"
        "Z2luZWVyQUkuCgrZhtmC2LfYqSDYrdix2KzYqTog2YXZhNmBIGRhdGFiYXNlLnB5INmK2YbYtNimINmF2K3YsdmR2YMg"
        "2YLYp9i52K/YqSDYp9mE2KjZitin2YbYp9iqINmI2KfZhNmF2KzZhNiv2KfYqiAqKtmE2K3YuNipCtin2YTYp9iz2KrZ"
        "itix2KfYryoqINin2LnYqtmF2KfYr9mL2Kcg2LnZhNmJINmF2KrYutmK2ZHYsSDYp9mE2KjZitim2KkgQVBQREFUQS4g"
        "2YTYsNmE2YMg2YrYrNioINi22KjYtyBBUFBEQVRBINi52YTZiQrZhdis2YTYryDZhdik2YLZkdiqICoq2YLYqNmEKiog"
        "2KPZiiDYp9iz2KrZitix2KfYryDZhNmE2YjYrdiv2KnYjCDZiNil2YTYpyDYudmF2YTYqiDYp9mE2KfYrtiq2KjYp9ix"
        "2KfYqiDYudmE2Ykg2YLYp9i52K/YqQrYqNmK2KfZhtin2Kog2KfZhNmF2LPYqtiu2K/ZhSDYp9mE2K3ZgtmK2YLZitip"
        "INmI2KPZgdiz2K/YqiDYqNmK2KfZhtin2KrZhy4KIiIiCgppbXBvcnQgb3MKaW1wb3J0IHN5cwppbXBvcnQgdGVtcGZp"
        "bGUKCiMg2YXYrNmE2K8g2YXYpNmC2ZHYqiDZhNmE2KfYrtiq2KjYp9ix2KfYqiDigJQg2YrZj9i22KjYtyDZgtio2YQg"
        "2KfYs9iq2YrYsdin2K8gZGF0YWJhc2Ug2KjYo9mKINi02YPZhApfVE1QID0gdGVtcGZpbGUubWtkdGVtcChwcmVmaXg9"
        "ImZpcmVhcHBfdGVzdHNfIikKb3MuZW52aXJvblsiQVBQREFUQSJdID0gX1RNUAoKIyDYpdiq2KfYrdipINin2LPYqtmK"
        "2LHYp9ivINmI2K3Yr9in2Kog2KfZhNmF2LTYsdmI2Lkg2YXZhiDZhdis2YTYryDYp9mE2KfYrtiq2KjYp9ix2KfYqgpz"
        "eXMucGF0aC5pbnNlcnQoMCwgb3MucGF0aC5kaXJuYW1lKG9zLnBhdGguZGlybmFtZShvcy5wYXRoLmFic3BhdGgoX19m"
        "aWxlX18pKSkpCgppbXBvcnQgcHl0ZXN0ICAjIG5vcWE6IEU0MDIKaW1wb3J0IGRhdGFiYXNlIGFzIGRiICAjIG5vcWE6"
        "IEU0MDIKCgpAcHl0ZXN0LmZpeHR1cmUKZGVmIHNlc3Npb24oKToKICAgICIiIgogICAg2KzZhNiz2Kkg2YLYp9i52K/Y"
        "qSDYqNmK2KfZhtin2Kog2YbYuNmK2YHYqSDZhNmD2YQg2KfYrtiq2KjYp9ixLgoKICAgINiq2Y/Zhti02KMg2KfZhNis"
        "2K/Yp9mI2YQg2KvZhSDYqtmP2K3YsNmBINio2LnYryDYp9mE2KfYrtiq2KjYp9ix2Iwg2YHZhNinINmK2KrYs9ix2ZHY"
        "qCDYo9ir2LEg2KfYrtiq2KjYp9ixINil2YTZiSDYotiu2LEuCiAgICAiIiIKICAgIGRiLkJhc2UubWV0YWRhdGEuY3Jl"
        "YXRlX2FsbChkYi5lbmdpbmUpCiAgICBzID0gZGIuU2Vzc2lvbkxvY2FsKCkKICAgIHRyeToKICAgICAgICB5aWVsZCBz"
        "CiAgICBmaW5hbGx5OgogICAgICAgIHMuY2xvc2UoKQogICAgICAgIGRiLkJhc2UubWV0YWRhdGEuZHJvcF9hbGwoZGIu"
        "ZW5naW5lKQoKCkBweXRlc3QuZml4dHVyZQpkZWYgY2xpZW50KHNlc3Npb24pOgogICAgYyA9IGRiLkNsaWVudChuYW1l"
        "PSLYtNix2YPYqSDYp9mE2LHZitin2LYg2YTZhNmF2YLYp9mI2YTYp9iqIiwgcGhvbmU9IjA1MDEyMzQ1NjciKQogICAg"
        "c2Vzc2lvbi5hZGQoYykKICAgIHNlc3Npb24uY29tbWl0KCkKICAgIHJldHVybiBjCgoKQHB5dGVzdC5maXh0dXJlCmRl"
        "ZiBwcm9qZWN0KHNlc3Npb24sIGNsaWVudCk6CiAgICBmcm9tIGRhdGV0aW1lIGltcG9ydCBkYXRlCiAgICBwID0gZGIu"
        "UHJvamVjdCgKICAgICAgICBuYW1lPSLYqNix2Kwg2KfZhNmF2YXZhNmD2KkgLSDZhti42KfZhSDYp9mE2KXZhtiw2KfY"
        "sSIsCiAgICAgICAgY2xpZW50X2lkPWNsaWVudC5pZCwgc3RhdHVzPSJJbnN0YWxsIiwKICAgICAgICBzdGFydF9kYXRl"
        "PWRhdGUoMjAyNiwgMSwgMSksIGVuZF9kYXRlPWRhdGUoMjAyNiwgMTIsIDMxKSwKICAgICkKICAgIHNlc3Npb24uYWRk"
        "KHApCiAgICBzZXNzaW9uLmNvbW1pdCgpCiAgICByZXR1cm4gcAo="
    ),
    'tests/test_equipment.py': (
        "IiIi2KfYrtiq2KjYp9ix2KfYqiDZhdmG2LfZgiDYp9mE2YXYudiv2KfYqiDZiNin2YTZgdit2LUg2KfZhNiv2YjYsdmK"
        "LiIiIgoKZnJvbSBkYXRldGltZSBpbXBvcnQgZGF0ZSwgdGltZWRlbHRhCgppbXBvcnQgZGF0YWJhc2UgYXMgZGIKCgpk"
        "ZWYgX2VxKHNlc3Npb24sIHByb2plY3QsICoqa3cpOgogICAgZSA9IGRiLkVxdWlwbWVudChwcm9qZWN0X2lkPXByb2pl"
        "Y3QuaWQsIG5hbWU9a3cucG9wKCJuYW1lIiwgIti32YHYp9mK2KkiKSwgKiprdykKICAgIHNlc3Npb24uYWRkKGUpCiAg"
        "ICBzZXNzaW9uLmNvbW1pdCgpCiAgICByZXR1cm4gZQoKCmNsYXNzIFRlc3RJbnNwZWN0aW9uRGF0ZXM6CgogICAgZGVm"
        "IHRlc3RfbmV4dF9pbnNwZWN0aW9uX2lzX2xhc3RfcGx1c19pbnRlcnZhbChzZWxmLCBzZXNzaW9uLCBwcm9qZWN0KToK"
        "ICAgICAgICBlID0gX2VxKHNlc3Npb24sIHByb2plY3QsCiAgICAgICAgICAgICAgICBsYXN0X2luc3BlY3Rpb25fZGF0"
        "ZT1kYXRlKDIwMjYsIDEsIDEpLCBpbnRlcnZhbF9kYXlzPTE4MCkKICAgICAgICBhc3NlcnQgZS5uZXh0X2luc3BlY3Rp"
        "b25fZGF0ZSA9PSBkYXRlKDIwMjYsIDYsIDMwKQoKICAgIGRlZiB0ZXN0X25vX2xhc3RfaW5zcGVjdGlvbl9tZWFuc19u"
        "b19uZXh0X2RhdGUoc2VsZiwgc2Vzc2lvbiwgcHJvamVjdCk6CiAgICAgICAgZSA9IF9lcShzZXNzaW9uLCBwcm9qZWN0"
        "LCBsYXN0X2luc3BlY3Rpb25fZGF0ZT1Ob25lLCBpbnRlcnZhbF9kYXlzPTE4MCkKICAgICAgICBhc3NlcnQgZS5uZXh0"
        "X2luc3BlY3Rpb25fZGF0ZSBpcyBOb25lCiAgICAgICAgYXNzZXJ0IGUuZGF5c191bnRpbF9kdWUgaXMgTm9uZQoKCmNs"
        "YXNzIFRlc3RBbGVydExldmVsOgogICAgIiIiCiAgICBhbGVydF9sZXZlbCDZh9mIINmF2Kcg2YrZhNmI2ZHZhiDYp9mE"
        "2LTYp9i02Kkg2YjYp9mE2KrZgtin2LHZitixINmI2YrYrdiv2ZHYryDZhdinINmK2LjZh9ixINmE2YTYr9mB2KfYuSDY"
        "p9mE2YXYr9mG2YrYjAogICAg2YHYo9mKINiu2YTZhCDZgdmK2Ycg2YrYudmG2Yog2YXYudiv2Kkg2YXYqtij2K7Ysdip"
        "INiq2KjYr9mIINiz2YTZitmF2KkuCiAgICAiIiIKCiAgICBkZWYgdGVzdF9vdmVyZHVlX3doZW5fcGFzdF9kdWUoc2Vs"
        "Ziwgc2Vzc2lvbiwgcHJvamVjdCk6CiAgICAgICAgZSA9IF9lcShzZXNzaW9uLCBwcm9qZWN0LAogICAgICAgICAgICAg"
        "ICAgbGFzdF9pbnNwZWN0aW9uX2RhdGU9ZGF0ZS50b2RheSgpIC0gdGltZWRlbHRhKGRheXM9NDAwKSwKICAgICAgICAg"
        "ICAgICAgIGludGVydmFsX2RheXM9MTgwKQogICAgICAgIGFzc2VydCBlLmFsZXJ0X2xldmVsID09ICJvdmVyZHVlIgog"
        "ICAgICAgIGFzc2VydCBlLmRheXNfdW50aWxfZHVlIDwgMAoKICAgIGRlZiB0ZXN0X3Nvb25fd2l0aGluXzMwX2RheXMo"
        "c2VsZiwgc2Vzc2lvbiwgcHJvamVjdCk6CiAgICAgICAgIyDZgdit2LUg2YLYqNmEIDE2MCDZitmI2YXZi9inINio2K/Z"
        "iNix2KkgMTgwID0+INmK2LPYqtit2YIg2KjYudivIDIwINmK2YjZhdmL2KcKICAgICAgICBlID0gX2VxKHNlc3Npb24s"
        "IHByb2plY3QsCiAgICAgICAgICAgICAgICBsYXN0X2luc3BlY3Rpb25fZGF0ZT1kYXRlLnRvZGF5KCkgLSB0aW1lZGVs"
        "dGEoZGF5cz0xNjApLAogICAgICAgICAgICAgICAgaW50ZXJ2YWxfZGF5cz0xODApCiAgICAgICAgYXNzZXJ0IGUuYWxl"
        "cnRfbGV2ZWwgPT0gInNvb24iCgogICAgZGVmIHRlc3Rfbm9uZV93aGVuX2NvbWZvcnRhYmx5X2FoZWFkKHNlbGYsIHNl"
        "c3Npb24sIHByb2plY3QpOgogICAgICAgIGUgPSBfZXEoc2Vzc2lvbiwgcHJvamVjdCwKICAgICAgICAgICAgICAgIGxh"
        "c3RfaW5zcGVjdGlvbl9kYXRlPWRhdGUudG9kYXkoKSwgaW50ZXJ2YWxfZGF5cz0xODApCiAgICAgICAgYXNzZXJ0IGUu"
        "YWxlcnRfbGV2ZWwgPT0gIm5vbmUiCgogICAgZGVmIHRlc3RfdW5rbm93bl93aGVuX25ldmVyX2luc3BlY3RlZChzZWxm"
        "LCBzZXNzaW9uLCBwcm9qZWN0KToKICAgICAgICAiIiLZhdi52K/YqSDYqNmE2Kcg2KrYp9ix2YrYriDZgdit2LUg2KPY"
        "rti32LEg2YXZhiDYp9mE2YXYqtij2K7YsdipIOKAlCDZitis2Kgg2KPZhNinINiq2Y/Yudin2YXZhCDZg9iz2YTZitmF"
        "2KkuIiIiCiAgICAgICAgZSA9IF9lcShzZXNzaW9uLCBwcm9qZWN0LCBsYXN0X2luc3BlY3Rpb25fZGF0ZT1Ob25lKQog"
        "ICAgICAgIGFzc2VydCBlLmFsZXJ0X2xldmVsID09ICJ1bmtub3duIgoKICAgIGRlZiB0ZXN0X2JvdW5kYXJ5X2V4YWN0"
        "bHlfMzBfZGF5c19pc19zb29uKHNlbGYsIHNlc3Npb24sIHByb2plY3QpOgogICAgICAgIGUgPSBfZXEoc2Vzc2lvbiwg"
        "cHJvamVjdCwKICAgICAgICAgICAgICAgIGxhc3RfaW5zcGVjdGlvbl9kYXRlPWRhdGUudG9kYXkoKSAtIHRpbWVkZWx0"
        "YShkYXlzPTE1MCksCiAgICAgICAgICAgICAgICBpbnRlcnZhbF9kYXlzPTE4MCkKICAgICAgICBhc3NlcnQgZS5kYXlz"
        "X3VudGlsX2R1ZSA9PSAzMAogICAgICAgIGFzc2VydCBlLmFsZXJ0X2xldmVsID09ICJzb29uIgoKICAgIGRlZiB0ZXN0"
        "X2JvdW5kYXJ5XzMxX2RheXNfaXNfbm90X3Nvb24oc2VsZiwgc2Vzc2lvbiwgcHJvamVjdCk6CiAgICAgICAgZSA9IF9l"
        "cShzZXNzaW9uLCBwcm9qZWN0LAogICAgICAgICAgICAgICAgbGFzdF9pbnNwZWN0aW9uX2RhdGU9ZGF0ZS50b2RheSgp"
        "IC0gdGltZWRlbHRhKGRheXM9MTQ5KSwKICAgICAgICAgICAgICAgIGludGVydmFsX2RheXM9MTgwKQogICAgICAgIGFz"
        "c2VydCBlLmRheXNfdW50aWxfZHVlID09IDMxCiAgICAgICAgYXNzZXJ0IGUuYWxlcnRfbGV2ZWwgPT0gIm5vbmUiCgoK"
        "Y2xhc3MgVGVzdFVwY29taW5nSW5zcGVjdGlvbnM6CgogICAgZGVmIHRlc3RfaW5jbHVkZXNfb3ZlcmR1ZV9zb29uX2Fu"
        "ZF91bmtub3duKHNlbGYsIHNlc3Npb24sIHByb2plY3QpOgogICAgICAgIF9lcShzZXNzaW9uLCBwcm9qZWN0LCBuYW1l"
        "PSLZhdiq2KPYrtix2KkiLAogICAgICAgICAgICBsYXN0X2luc3BlY3Rpb25fZGF0ZT1kYXRlLnRvZGF5KCkgLSB0aW1l"
        "ZGVsdGEoZGF5cz00MDApLAogICAgICAgICAgICBpbnRlcnZhbF9kYXlzPTE4MCkKICAgICAgICBfZXEoc2Vzc2lvbiwg"
        "cHJvamVjdCwgbmFtZT0i2YLYsdmK2KjYqSIsCiAgICAgICAgICAgIGxhc3RfaW5zcGVjdGlvbl9kYXRlPWRhdGUudG9k"
        "YXkoKSAtIHRpbWVkZWx0YShkYXlzPTE2MCksCiAgICAgICAgICAgIGludGVydmFsX2RheXM9MTgwKQogICAgICAgIF9l"
        "cShzZXNzaW9uLCBwcm9qZWN0LCBuYW1lPSLZhNmFINiq2YHYrdi1IiwgbGFzdF9pbnNwZWN0aW9uX2RhdGU9Tm9uZSkK"
        "ICAgICAgICBfZXEoc2Vzc2lvbiwgcHJvamVjdCwgbmFtZT0i2LPZhNmK2YXYqSIsCiAgICAgICAgICAgIGxhc3RfaW5z"
        "cGVjdGlvbl9kYXRlPWRhdGUudG9kYXkoKSwgaW50ZXJ2YWxfZGF5cz0xODApCgogICAgICAgIG5hbWVzID0gW2UubmFt"
        "ZSBmb3IgZSBpbiBkYi51cGNvbWluZ19pbnNwZWN0aW9ucyhzZXNzaW9uKV0KICAgICAgICBhc3NlcnQgItiz2YTZitmF"
        "2KkiIG5vdCBpbiBuYW1lcwogICAgICAgIGFzc2VydCBzZXQobmFtZXMpID09IHsi2YXYqtij2K7YsdipIiwgItmC2LHZ"
        "itio2KkiLCAi2YTZhSDYqtmB2K3YtSJ9CgogICAgZGVmIHRlc3Rfb3ZlcmR1ZV9zb3J0ZWRfZmlyc3Qoc2VsZiwgc2Vz"
        "c2lvbiwgcHJvamVjdCk6CiAgICAgICAgX2VxKHNlc3Npb24sIHByb2plY3QsIG5hbWU9ItmC2LHZitio2KkiLAogICAg"
        "ICAgICAgICBsYXN0X2luc3BlY3Rpb25fZGF0ZT1kYXRlLnRvZGF5KCkgLSB0aW1lZGVsdGEoZGF5cz0xNjApLAogICAg"
        "ICAgICAgICBpbnRlcnZhbF9kYXlzPTE4MCkKICAgICAgICBfZXEoc2Vzc2lvbiwgcHJvamVjdCwgbmFtZT0i2YXYqtij"
        "2K7YsdipIiwKICAgICAgICAgICAgbGFzdF9pbnNwZWN0aW9uX2RhdGU9ZGF0ZS50b2RheSgpIC0gdGltZWRlbHRhKGRh"
        "eXM9NDAwKSwKICAgICAgICAgICAgaW50ZXJ2YWxfZGF5cz0xODApCiAgICAgICAgYXNzZXJ0IGRiLnVwY29taW5nX2lu"
        "c3BlY3Rpb25zKHNlc3Npb24pWzBdLm5hbWUgPT0gItmF2KrYo9iu2LHYqSIK"
    ),
    'tests/test_contracts.py': (
        "IiIi2KfYrtiq2KjYp9ix2KfYqiDYudmC2YjYryDYp9mE2LXZitin2YbYqSDYp9mE2LPZhtmI2YrYqSDZiNiy2YrYp9ix"
        "2KfYqtmH2KcuIiIiCgpmcm9tIGRhdGV0aW1lIGltcG9ydCBkYXRlLCB0aW1lZGVsdGEKCmltcG9ydCBkYXRhYmFzZSBh"
        "cyBkYgoKCmRlZiBfY29udHJhY3Qoc2Vzc2lvbiwgY2xpZW50LCAqKmt3KToKICAgIGt3LnNldGRlZmF1bHQoInN0YXJ0"
        "X2RhdGUiLCBkYXRlLnRvZGF5KCkgLSB0aW1lZGVsdGEoZGF5cz0zMCkpCiAgICBrdy5zZXRkZWZhdWx0KCJlbmRfZGF0"
        "ZSIsIGRhdGUudG9kYXkoKSArIHRpbWVkZWx0YShkYXlzPTMzNSkpCiAgICBrdy5zZXRkZWZhdWx0KCJzdGF0dXMiLCAi"
        "QWN0aXZlIikKICAgIGt3LnNldGRlZmF1bHQoInZpc2l0c19wZXJfeWVhciIsIDQpCiAgICBjID0gZGIuQ29udHJhY3Qo"
        "Y2xpZW50X2lkPWNsaWVudC5pZCwgKiprdykKICAgIHNlc3Npb24uYWRkKGMpCiAgICBzZXNzaW9uLmNvbW1pdCgpCiAg"
        "ICByZXR1cm4gYwoKCmNsYXNzIFRlc3RDb250cmFjdFN0YXR1czoKCiAgICBkZWYgdGVzdF9hY3RpdmVfd2l0aGluX3Bl"
        "cmlvZChzZWxmLCBzZXNzaW9uLCBjbGllbnQpOgogICAgICAgIGFzc2VydCBfY29udHJhY3Qoc2Vzc2lvbiwgY2xpZW50"
        "KS5pc19hY3RpdmUgaXMgVHJ1ZQoKICAgIGRlZiB0ZXN0X25vdF9hY3RpdmVfYWZ0ZXJfZW5kKHNlbGYsIHNlc3Npb24s"
        "IGNsaWVudCk6CiAgICAgICAgYyA9IF9jb250cmFjdChzZXNzaW9uLCBjbGllbnQsCiAgICAgICAgICAgICAgICAgICAg"
        "ICBzdGFydF9kYXRlPWRhdGUoMjAyNSwgMSwgMSksIGVuZF9kYXRlPWRhdGUoMjAyNSwgMTIsIDMxKSkKICAgICAgICBh"
        "c3NlcnQgYy5pc19hY3RpdmUgaXMgRmFsc2UKICAgICAgICBhc3NlcnQgYy5hbGVydF9sZXZlbCA9PSAiZXhwaXJlZCIK"
        "CiAgICBkZWYgdGVzdF9ub3RfYWN0aXZlX2JlZm9yZV9zdGFydChzZWxmLCBzZXNzaW9uLCBjbGllbnQpOgogICAgICAg"
        "IGMgPSBfY29udHJhY3Qoc2Vzc2lvbiwgY2xpZW50LAogICAgICAgICAgICAgICAgICAgICAgc3RhcnRfZGF0ZT1kYXRl"
        "LnRvZGF5KCkgKyB0aW1lZGVsdGEoZGF5cz0xMCksCiAgICAgICAgICAgICAgICAgICAgICBlbmRfZGF0ZT1kYXRlLnRv"
        "ZGF5KCkgKyB0aW1lZGVsdGEoZGF5cz0zNzUpKQogICAgICAgIGFzc2VydCBjLmlzX2FjdGl2ZSBpcyBGYWxzZQoKICAg"
        "IGRlZiB0ZXN0X2NhbmNlbGxlZF9pc19uZXZlcl9hY3RpdmUoc2VsZiwgc2Vzc2lvbiwgY2xpZW50KToKICAgICAgICBj"
        "ID0gX2NvbnRyYWN0KHNlc3Npb24sIGNsaWVudCwgc3RhdHVzPSJDYW5jZWxsZWQiKQogICAgICAgIGFzc2VydCBjLmlz"
        "X2FjdGl2ZSBpcyBGYWxzZQoKICAgIGRlZiB0ZXN0X2NhbmNlbGxlZF9zaG93c19pbmFjdGl2ZV9ub3RfdmFsaWQoc2Vs"
        "Ziwgc2Vzc2lvbiwgY2xpZW50KToKICAgICAgICAiIiIKICAgICAgICDYudmC2K8g2YXZhNi62Ykg2YPYp9mGINmK2LjZ"
        "h9ixICLYs9in2LHZiiIg2YHZiiDYrtin2YbYqSDYp9mE2LPYsdmK2KfZhiDZhNij2YYgYWxlcnRfbGV2ZWwg2KPYudin"
        "2K8KICAgICAgICAibm9uZSIg4oCUINmI2YfZiiDYp9mE2YLZitmF2Kkg2YbZgdiz2YfYpyDYp9mE2KrZiiDYqti52YbZ"
        "iiAi2LbZhdmGINin2YTZhdiv2KkiLgogICAgICAgICIiIgogICAgICAgIGMgPSBfY29udHJhY3Qoc2Vzc2lvbiwgY2xp"
        "ZW50LCBzdGF0dXM9IkNhbmNlbGxlZCIpCiAgICAgICAgYXNzZXJ0IGMuYWxlcnRfbGV2ZWwgPT0gImluYWN0aXZlIgoK"
        "ICAgIGRlZiB0ZXN0X3N1c3BlbmRlZF9pc19pbmFjdGl2ZShzZWxmLCBzZXNzaW9uLCBjbGllbnQpOgogICAgICAgIGFz"
        "c2VydCBfY29udHJhY3Qoc2Vzc2lvbiwgY2xpZW50LCBzdGF0dXM9IlN1c3BlbmRlZCIpLmFsZXJ0X2xldmVsID09ICJp"
        "bmFjdGl2ZSIKCiAgICBkZWYgdGVzdF9zb29uX3dpdGhpbl82MF9kYXlzKHNlbGYsIHNlc3Npb24sIGNsaWVudCk6CiAg"
        "ICAgICAgYyA9IF9jb250cmFjdChzZXNzaW9uLCBjbGllbnQsCiAgICAgICAgICAgICAgICAgICAgICBzdGFydF9kYXRl"
        "PWRhdGUudG9kYXkoKSAtIHRpbWVkZWx0YShkYXlzPTMwMCksCiAgICAgICAgICAgICAgICAgICAgICBlbmRfZGF0ZT1k"
        "YXRlLnRvZGF5KCkgKyB0aW1lZGVsdGEoZGF5cz00NSkpCiAgICAgICAgYXNzZXJ0IGMuYWxlcnRfbGV2ZWwgPT0gInNv"
        "b24iCiAgICAgICAgYXNzZXJ0IGMuZGF5c19yZW1haW5pbmcgPT0gNDUKCiAgICBkZWYgdGVzdF91bmtub3duX3dpdGhv"
        "dXRfZW5kX2RhdGUoc2VsZiwgc2Vzc2lvbiwgY2xpZW50KToKICAgICAgICBhc3NlcnQgX2NvbnRyYWN0KHNlc3Npb24s"
        "IGNsaWVudCwgZW5kX2RhdGU9Tm9uZSkuYWxlcnRfbGV2ZWwgPT0gInVua25vd24iCgogICAgZGVmIHRlc3RfYm91bmRh"
        "cnlfNjBfZGF5c19pc19zb29uKHNlbGYsIHNlc3Npb24sIGNsaWVudCk6CiAgICAgICAgYyA9IF9jb250cmFjdChzZXNz"
        "aW9uLCBjbGllbnQsIGVuZF9kYXRlPWRhdGUudG9kYXkoKSArIHRpbWVkZWx0YShkYXlzPTYwKSkKICAgICAgICBhc3Nl"
        "cnQgYy5hbGVydF9sZXZlbCA9PSAic29vbiIKCiAgICBkZWYgdGVzdF9ib3VuZGFyeV82MV9kYXlzX2lzX25vcm1hbChz"
        "ZWxmLCBzZXNzaW9uLCBjbGllbnQpOgogICAgICAgIGMgPSBfY29udHJhY3Qoc2Vzc2lvbiwgY2xpZW50LCBlbmRfZGF0"
        "ZT1kYXRlLnRvZGF5KCkgKyB0aW1lZGVsdGEoZGF5cz02MSkpCiAgICAgICAgYXNzZXJ0IGMuYWxlcnRfbGV2ZWwgPT0g"
        "Im5vbmUiCgoKY2xhc3MgVGVzdFZpc2l0czoKCiAgICBkZWYgdGVzdF9jb3VudHNfb25seV9kb25lX3Zpc2l0cyhzZWxm"
        "LCBzZXNzaW9uLCBjbGllbnQpOgogICAgICAgIGMgPSBfY29udHJhY3Qoc2Vzc2lvbiwgY2xpZW50LCB2aXNpdHNfcGVy"
        "X3llYXI9NCkKICAgICAgICBzZXNzaW9uLmFkZF9hbGwoWwogICAgICAgICAgICBkYi5Db250cmFjdFZpc2l0KGNvbnRy"
        "YWN0X2lkPWMuaWQsIHZpc2l0X2RhdGU9ZGF0ZS50b2RheSgpLCBzdGF0dXM9IkRvbmUiKSwKICAgICAgICAgICAgZGIu"
        "Q29udHJhY3RWaXNpdChjb250cmFjdF9pZD1jLmlkLCB2aXNpdF9kYXRlPWRhdGUudG9kYXkoKSwgc3RhdHVzPSJTY2hl"
        "ZHVsZWQiKSwKICAgICAgICAgICAgZGIuQ29udHJhY3RWaXNpdChjb250cmFjdF9pZD1jLmlkLCB2aXNpdF9kYXRlPWRh"
        "dGUudG9kYXkoKSwgc3RhdHVzPSJNaXNzZWQiKSwKICAgICAgICBdKQogICAgICAgIHNlc3Npb24uY29tbWl0KCkKICAg"
        "ICAgICBzZXNzaW9uLnJlZnJlc2goYykKICAgICAgICBhc3NlcnQgYy52aXNpdHNfZG9uZSA9PSAxCiAgICAgICAgYXNz"
        "ZXJ0IGMudmlzaXRzX3JlbWFpbmluZyA9PSAzCgogICAgZGVmIHRlc3RfcmVtYWluaW5nX25ldmVyX25lZ2F0aXZlKHNl"
        "bGYsIHNlc3Npb24sIGNsaWVudCk6CiAgICAgICAgIiIi2KrZhtmB2YrYsCDYstmK2KfYsdin2Kog2KPZg9ir2LEg2YXZ"
        "hiDYp9mE2YXYqti52KfZgtivINi52YTZitmHINmK2KzYqCDYo9mE2Kcg2YrZhtiq2Kwg2LHZgtmF2YvYpyDYs9in2YTY"
        "qNmL2KcuIiIiCiAgICAgICAgYyA9IF9jb250cmFjdChzZXNzaW9uLCBjbGllbnQsIHZpc2l0c19wZXJfeWVhcj0xKQog"
        "ICAgICAgIHNlc3Npb24uYWRkX2FsbChbCiAgICAgICAgICAgIGRiLkNvbnRyYWN0VmlzaXQoY29udHJhY3RfaWQ9Yy5p"
        "ZCwgdmlzaXRfZGF0ZT1kYXRlLnRvZGF5KCksIHN0YXR1cz0iRG9uZSIpLAogICAgICAgICAgICBkYi5Db250cmFjdFZp"
        "c2l0KGNvbnRyYWN0X2lkPWMuaWQsIHZpc2l0X2RhdGU9ZGF0ZS50b2RheSgpLCBzdGF0dXM9IkRvbmUiKSwKICAgICAg"
        "ICBdKQogICAgICAgIHNlc3Npb24uY29tbWl0KCkKICAgICAgICBzZXNzaW9uLnJlZnJlc2goYykKICAgICAgICBhc3Nl"
        "cnQgYy52aXNpdHNfcmVtYWluaW5nID09IDAKCiAgICBkZWYgdGVzdF9uZXh0X3Zpc2l0X2lzX2VhcmxpZXN0X3NjaGVk"
        "dWxlZChzZWxmLCBzZXNzaW9uLCBjbGllbnQpOgogICAgICAgIGMgPSBfY29udHJhY3Qoc2Vzc2lvbiwgY2xpZW50KQog"
        "ICAgICAgIHNlc3Npb24uYWRkX2FsbChbCiAgICAgICAgICAgIGRiLkNvbnRyYWN0VmlzaXQoY29udHJhY3RfaWQ9Yy5p"
        "ZCwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICB2aXNpdF9kYXRlPWRhdGUudG9kYXkoKSArIHRpbWVkZWx0YShk"
        "YXlzPTYwKSwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICBzdGF0dXM9IlNjaGVkdWxlZCIpLAogICAgICAgICAg"
        "ICBkYi5Db250cmFjdFZpc2l0KGNvbnRyYWN0X2lkPWMuaWQsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgdmlz"
        "aXRfZGF0ZT1kYXRlLnRvZGF5KCkgKyB0aW1lZGVsdGEoZGF5cz0yMCksCiAgICAgICAgICAgICAgICAgICAgICAgICAg"
        "ICAgc3RhdHVzPSJTY2hlZHVsZWQiKSwKICAgICAgICAgICAgZGIuQ29udHJhY3RWaXNpdChjb250cmFjdF9pZD1jLmlk"
        "LAogICAgICAgICAgICAgICAgICAgICAgICAgICAgIHZpc2l0X2RhdGU9ZGF0ZS50b2RheSgpICsgdGltZWRlbHRhKGRh"
        "eXM9NSksCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgc3RhdHVzPSJEb25lIiksCiAgICAgICAgXSkKICAgICAg"
        "ICBzZXNzaW9uLmNvbW1pdCgpCiAgICAgICAgc2Vzc2lvbi5yZWZyZXNoKGMpCiAgICAgICAgYXNzZXJ0IGMubmV4dF92"
        "aXNpdF9kYXRlID09IGRhdGUudG9kYXkoKSArIHRpbWVkZWx0YShkYXlzPTIwKQoKICAgIGRlZiB0ZXN0X3NjaGVkdWxl"
        "ZF9wYXN0X2RhdGVfaXNfb3ZlcmR1ZShzZWxmLCBzZXNzaW9uLCBjbGllbnQpOgogICAgICAgIGMgPSBfY29udHJhY3Qo"
        "c2Vzc2lvbiwgY2xpZW50KQogICAgICAgIHYgPSBkYi5Db250cmFjdFZpc2l0KGNvbnRyYWN0X2lkPWMuaWQsCiAgICAg"
        "ICAgICAgICAgICAgICAgICAgICAgICAgdmlzaXRfZGF0ZT1kYXRlLnRvZGF5KCkgLSB0aW1lZGVsdGEoZGF5cz01KSwK"
        "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICBzdGF0dXM9IlNjaGVkdWxlZCIpCiAgICAgICAgc2Vzc2lvbi5hZGQo"
        "dikKICAgICAgICBzZXNzaW9uLmNvbW1pdCgpCiAgICAgICAgYXNzZXJ0IHYuaXNfb3ZlcmR1ZSBpcyBUcnVlCgogICAg"
        "ZGVmIHRlc3RfZG9uZV92aXNpdF9uZXZlcl9vdmVyZHVlKHNlbGYsIHNlc3Npb24sIGNsaWVudCk6CiAgICAgICAgYyA9"
        "IF9jb250cmFjdChzZXNzaW9uLCBjbGllbnQpCiAgICAgICAgdiA9IGRiLkNvbnRyYWN0VmlzaXQoY29udHJhY3RfaWQ9"
        "Yy5pZCwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICB2aXNpdF9kYXRlPWRhdGUudG9kYXkoKSAtIHRpbWVkZWx0"
        "YShkYXlzPTEwMCksCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgc3RhdHVzPSJEb25lIikKICAgICAgICBzZXNz"
        "aW9uLmFkZCh2KQogICAgICAgIHNlc3Npb24uY29tbWl0KCkKICAgICAgICBhc3NlcnQgdi5pc19vdmVyZHVlIGlzIEZh"
        "bHNlCgogICAgZGVmIHRlc3RfZGVsZXRpbmdfY29udHJhY3RfcmVtb3Zlc19pdHNfdmlzaXRzKHNlbGYsIHNlc3Npb24s"
        "IGNsaWVudCk6CiAgICAgICAgYyA9IF9jb250cmFjdChzZXNzaW9uLCBjbGllbnQpCiAgICAgICAgc2Vzc2lvbi5hZGQo"
        "ZGIuQ29udHJhY3RWaXNpdChjb250cmFjdF9pZD1jLmlkLCB2aXNpdF9kYXRlPWRhdGUudG9kYXkoKSkpCiAgICAgICAg"
        "c2Vzc2lvbi5jb21taXQoKQogICAgICAgIHNlc3Npb24uZGVsZXRlKGMpCiAgICAgICAgc2Vzc2lvbi5jb21taXQoKQog"
        "ICAgICAgIGFzc2VydCBzZXNzaW9uLnF1ZXJ5KGRiLkNvbnRyYWN0VmlzaXQpLmNvdW50KCkgPT0gMAoKCmNsYXNzIFRl"
        "c3RDb250cmFjdEZpbmFuY2U6CgogICAgZGVmIHRlc3RfdG90YWxzX2Zyb21fbGlua2VkX2ludm9pY2VzKHNlbGYsIHNl"
        "c3Npb24sIGNsaWVudCwgcHJvamVjdCk6CiAgICAgICAgYyA9IF9jb250cmFjdChzZXNzaW9uLCBjbGllbnQsIHZhbHVl"
        "PTEyMDAwMCkKICAgICAgICBzZXNzaW9uLmFkZF9hbGwoWwogICAgICAgICAgICBkYi5JbnZvaWNlKHByb2plY3RfaWQ9"
        "cHJvamVjdC5pZCwgY29udHJhY3RfaWQ9Yy5pZCwKICAgICAgICAgICAgICAgICAgICAgICBhbW91bnQ9MzAwMDAsIHN0"
        "YXR1cz0iUGFpZCIpLAogICAgICAgICAgICBkYi5JbnZvaWNlKHByb2plY3RfaWQ9cHJvamVjdC5pZCwgY29udHJhY3Rf"
        "aWQ9Yy5pZCwKICAgICAgICAgICAgICAgICAgICAgICBhbW91bnQ9MjAwMDAsIHN0YXR1cz0iVW5wYWlkIiksCiAgICAg"
        "ICAgICAgIGRiLkludm9pY2UocHJvamVjdF9pZD1wcm9qZWN0LmlkLCBhbW91bnQ9OTk5OTksCiAgICAgICAgICAgICAg"
        "ICAgICAgICAgc3RhdHVzPSJVbnBhaWQiKSwgICMg2LrZitixINmF2LHYqtio2LfYqSDYqNin2YTYudmC2K8KICAgICAg"
        "ICBdKQogICAgICAgIHNlc3Npb24uY29tbWl0KCkKICAgICAgICBzZXNzaW9uLnJlZnJlc2goYykKICAgICAgICBhc3Nl"
        "cnQgYy50b3RhbF9pbnZvaWNlZCA9PSA1MDAwMAogICAgICAgIGFzc2VydCBjLnRvdGFsX3VucGFpZCA9PSAyMDAwMAoK"
        "ICAgIGRlZiB0ZXN0X2RlbGV0aW5nX2NvbnRyYWN0X2tlZXBzX2ludm9pY2Uoc2VsZiwgc2Vzc2lvbiwgY2xpZW50LCBw"
        "cm9qZWN0KToKICAgICAgICAiIiLYrdiw2YEg2KfZhNi52YLYryDZitis2Kgg2KPZhNinINmK2K3YsNmBINmB2YjYp9iq"
        "2YrYsdmHIOKAlCDYrti32LEg2YHZgtiv2KfZhiDYqNmK2KfZhtin2Kog2YXYp9mE2YrYqS4iIiIKICAgICAgICBjID0g"
        "X2NvbnRyYWN0KHNlc3Npb24sIGNsaWVudCkKICAgICAgICBpbnYgPSBkYi5JbnZvaWNlKHByb2plY3RfaWQ9cHJvamVj"
        "dC5pZCwgY29udHJhY3RfaWQ9Yy5pZCwgYW1vdW50PTUwMDApCiAgICAgICAgc2Vzc2lvbi5hZGQoaW52KQogICAgICAg"
        "IHNlc3Npb24uY29tbWl0KCkKCiAgICAgICAgaW52LmNvbnRyYWN0X2lkID0gTm9uZSAgICAgICMg2YPZhdinINiq2YHY"
        "udmEINin2YTZiNin2KzZh9ipINmC2KjZhCDYp9mE2K3YsNmBCiAgICAgICAgc2Vzc2lvbi5kZWxldGUoYykKICAgICAg"
        "ICBzZXNzaW9uLmNvbW1pdCgpCgogICAgICAgIGFzc2VydCBzZXNzaW9uLnF1ZXJ5KGRiLkludm9pY2UpLmNvdW50KCkg"
        "PT0gMQogICAgICAgIGFzc2VydCBzZXNzaW9uLnF1ZXJ5KGRiLkludm9pY2UpLmZpcnN0KCkuY29udHJhY3RfaWQgaXMg"
        "Tm9uZQoKCmNsYXNzIFRlc3RDb250cmFjdFF1ZXJpZXM6CgogICAgZGVmIHRlc3RfZXhwaXJpbmdfZXhjbHVkZXNfY2Fu"
        "Y2VsbGVkKHNlbGYsIHNlc3Npb24sIGNsaWVudCk6CiAgICAgICAgX2NvbnRyYWN0KHNlc3Npb24sIGNsaWVudCwgc3Rh"
        "dHVzPSJDYW5jZWxsZWQiLAogICAgICAgICAgICAgICAgICBlbmRfZGF0ZT1kYXRlLnRvZGF5KCkgLSB0aW1lZGVsdGEo"
        "ZGF5cz01KSkKICAgICAgICBfY29udHJhY3Qoc2Vzc2lvbiwgY2xpZW50LCBzdGF0dXM9IkFjdGl2ZSIsCiAgICAgICAg"
        "ICAgICAgICAgIGVuZF9kYXRlPWRhdGUudG9kYXkoKSArIHRpbWVkZWx0YShkYXlzPTEwKSkKICAgICAgICByZXN1bHQg"
        "PSBkYi5leHBpcmluZ19jb250cmFjdHMoc2Vzc2lvbikKICAgICAgICBhc3NlcnQgbGVuKHJlc3VsdCkgPT0gMQogICAg"
        "ICAgIGFzc2VydCByZXN1bHRbMF0uc3RhdHVzID09ICJBY3RpdmUiCgogICAgZGVmIHRlc3Rfc2VhcmNoX2J5X251bWJl"
        "cl9hbmRfc3RhdHVzKHNlbGYsIHNlc3Npb24sIGNsaWVudCk6CiAgICAgICAgX2NvbnRyYWN0KHNlc3Npb24sIGNsaWVu"
        "dCwgY29udHJhY3RfbnVtYmVyPSJBTUMtMjAyNi0wMDEiLAogICAgICAgICAgICAgICAgICB0aXRsZT0i2LnZgtivINio"
        "2LHYrCDYp9mE2YXZhdmE2YPYqSIpCiAgICAgICAgX2NvbnRyYWN0KHNlc3Npb24sIGNsaWVudCwgY29udHJhY3RfbnVt"
        "YmVyPSJBTUMtMjAyNi0wMDIiLAogICAgICAgICAgICAgICAgICB0aXRsZT0i2LnZgtivINin2YTZiNin2K3YqSIsIHN0"
        "YXR1cz0iQ2FuY2VsbGVkIikKCiAgICAgICAgYXNzZXJ0IGxlbihkYi5zZWFyY2hfY29udHJhY3RzKHNlc3Npb24sIHRl"
        "eHQ9IjAwMSIpKSA9PSAxCiAgICAgICAgYXNzZXJ0IGxlbihkYi5zZWFyY2hfY29udHJhY3RzKHNlc3Npb24sIHRleHQ9"
        "Itin2YTZiNin2K3YqSIpKSA9PSAxCiAgICAgICAgYXNzZXJ0IGxlbihkYi5zZWFyY2hfY29udHJhY3RzKHNlc3Npb24s"
        "IHN0YXR1cz0iQWN0aXZlIikpID09IDEKICAgICAgICBhc3NlcnQgbGVuKGRiLnNlYXJjaF9jb250cmFjdHMoc2Vzc2lv"
        "bikpID09IDIKCiAgICBkZWYgdGVzdF9kdWVfdmlzaXRzX2lnbm9yZXNfZmFyX2Z1dHVyZShzZWxmLCBzZXNzaW9uLCBj"
        "bGllbnQpOgogICAgICAgIGMgPSBfY29udHJhY3Qoc2Vzc2lvbiwgY2xpZW50KQogICAgICAgIHNlc3Npb24uYWRkX2Fs"
        "bChbCiAgICAgICAgICAgIGRiLkNvbnRyYWN0VmlzaXQoY29udHJhY3RfaWQ9Yy5pZCwKICAgICAgICAgICAgICAgICAg"
        "ICAgICAgICAgICB2aXNpdF9kYXRlPWRhdGUudG9kYXkoKSArIHRpbWVkZWx0YShkYXlzPTUpLAogICAgICAgICAgICAg"
        "ICAgICAgICAgICAgICAgIHN0YXR1cz0iU2NoZWR1bGVkIiksCiAgICAgICAgICAgIGRiLkNvbnRyYWN0VmlzaXQoY29u"
        "dHJhY3RfaWQ9Yy5pZCwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICB2aXNpdF9kYXRlPWRhdGUudG9kYXkoKSAr"
        "IHRpbWVkZWx0YShkYXlzPTIwMCksCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgc3RhdHVzPSJTY2hlZHVsZWQi"
        "KSwKICAgICAgICBdKQogICAgICAgIHNlc3Npb24uY29tbWl0KCkKICAgICAgICBhc3NlcnQgbGVuKGRiLmR1ZV9jb250"
        "cmFjdF92aXNpdHMoc2Vzc2lvbiwgd2l0aGluX2RheXM9MzApKSA9PSAxCg=="
    ),
    'tests/test_invoices_and_stats.py': (
        "IiIi2KfYrtiq2KjYp9ix2KfYqiDYp9mE2YHZiNin2KrZitix2Iwg2KXYrdi12KfYodin2Kog2YTZiNit2Kkg2KfZhNmF"
        "2LnZhNmI2YXYp9iq2Iwg2YjYs9mE2KfZhdipINin2YTYudmE2KfZgtin2KouIiIiCgpmcm9tIGRhdGV0aW1lIGltcG9y"
        "dCBkYXRlLCB0aW1lZGVsdGEKCmltcG9ydCBkYXRhYmFzZSBhcyBkYgoKCmNsYXNzIFRlc3RJbnZvaWNlczoKCiAgICBk"
        "ZWYgdGVzdF91bnBhaWRfcGFzdF9kdWVfaXNfb3ZlcmR1ZShzZWxmLCBzZXNzaW9uLCBwcm9qZWN0KToKICAgICAgICBp"
        "ID0gZGIuSW52b2ljZShwcm9qZWN0X2lkPXByb2plY3QuaWQsIGFtb3VudD0xMDAwLCBzdGF0dXM9IlVucGFpZCIsCiAg"
        "ICAgICAgICAgICAgICAgICAgICAgZHVlX2RhdGU9ZGF0ZS50b2RheSgpIC0gdGltZWRlbHRhKGRheXM9MSkpCiAgICAg"
        "ICAgc2Vzc2lvbi5hZGQoaSkKICAgICAgICBzZXNzaW9uLmNvbW1pdCgpCiAgICAgICAgYXNzZXJ0IGkuaXNfb3ZlcmR1"
        "ZSBpcyBUcnVlCgogICAgZGVmIHRlc3RfcGFpZF9pbnZvaWNlX25ldmVyX292ZXJkdWUoc2VsZiwgc2Vzc2lvbiwgcHJv"
        "amVjdCk6CiAgICAgICAgIiIi2YHYp9iq2YjYsdipINmF2LPYr9mO2ZHYr9ipINmK2KzYqCDYo9mE2Kcg2KrYuNmH2LEg"
        "2YXYqtij2K7YsdipINmF2YfZhdinINmF2LbZiSDYudmE2Ykg2KrYp9ix2YrYrtmH2KcuIiIiCiAgICAgICAgaSA9IGRi"
        "Lkludm9pY2UocHJvamVjdF9pZD1wcm9qZWN0LmlkLCBhbW91bnQ9MTAwMCwgc3RhdHVzPSJQYWlkIiwKICAgICAgICAg"
        "ICAgICAgICAgICAgICBkdWVfZGF0ZT1kYXRlLnRvZGF5KCkgLSB0aW1lZGVsdGEoZGF5cz0zNjUpKQogICAgICAgIHNl"
        "c3Npb24uYWRkKGkpCiAgICAgICAgc2Vzc2lvbi5jb21taXQoKQogICAgICAgIGFzc2VydCBpLmlzX292ZXJkdWUgaXMg"
        "RmFsc2UKCiAgICBkZWYgdGVzdF9ub19kdWVfZGF0ZV9pc19ub3Rfb3ZlcmR1ZShzZWxmLCBzZXNzaW9uLCBwcm9qZWN0"
        "KToKICAgICAgICBpID0gZGIuSW52b2ljZShwcm9qZWN0X2lkPXByb2plY3QuaWQsIGFtb3VudD0xMDAwLAogICAgICAg"
        "ICAgICAgICAgICAgICAgIHN0YXR1cz0iVW5wYWlkIiwgZHVlX2RhdGU9Tm9uZSkKICAgICAgICBzZXNzaW9uLmFkZChp"
        "KQogICAgICAgIHNlc3Npb24uY29tbWl0KCkKICAgICAgICBhc3NlcnQgaS5pc19vdmVyZHVlIGlzIEZhbHNlCgogICAg"
        "ZGVmIHRlc3RfcHJvamVjdF90b3RhbHMoc2VsZiwgc2Vzc2lvbiwgcHJvamVjdCk6CiAgICAgICAgc2Vzc2lvbi5hZGRf"
        "YWxsKFsKICAgICAgICAgICAgZGIuSW52b2ljZShwcm9qZWN0X2lkPXByb2plY3QuaWQsIGFtb3VudD01MDAwLCBzdGF0"
        "dXM9IlBhaWQiKSwKICAgICAgICAgICAgZGIuSW52b2ljZShwcm9qZWN0X2lkPXByb2plY3QuaWQsIGFtb3VudD0zMDAw"
        "LCBzdGF0dXM9IlVucGFpZCIpLAogICAgICAgIF0pCiAgICAgICAgc2Vzc2lvbi5jb21taXQoKQogICAgICAgIHNlc3Np"
        "b24ucmVmcmVzaChwcm9qZWN0KQogICAgICAgIGFzc2VydCBwcm9qZWN0LnRvdGFsX2ludm9pY2VkID09IDgwMDAKICAg"
        "ICAgICBhc3NlcnQgcHJvamVjdC50b3RhbF91bnBhaWQgPT0gMzAwMAoKICAgIGRlZiB0ZXN0X25vbmVfYW1vdW50X2Rv"
        "ZXNfbm90X2NyYXNoX3RvdGFscyhzZWxmLCBzZXNzaW9uLCBwcm9qZWN0KToKICAgICAgICAiIiLZgtmK2YXYqSDZgdin"
        "2LHYutipINmK2KzYqCDYo9mGINiq2Y/Yudin2YXZhCDZg9i12YHYsSDZhNinINij2YYg2KrZj9iz2YLYtyDYp9mE2K3Y"
        "s9in2KguIiIiCiAgICAgICAgc2Vzc2lvbi5hZGQoZGIuSW52b2ljZShwcm9qZWN0X2lkPXByb2plY3QuaWQsIGFtb3Vu"
        "dD1Ob25lLCBzdGF0dXM9IlVucGFpZCIpKQogICAgICAgIHNlc3Npb24uY29tbWl0KCkKICAgICAgICBzZXNzaW9uLnJl"
        "ZnJlc2gocHJvamVjdCkKICAgICAgICBhc3NlcnQgcHJvamVjdC50b3RhbF9pbnZvaWNlZCA9PSAwCgoKY2xhc3MgVGVz"
        "dFJlbGF0aW9uc2hpcHM6CgogICAgZGVmIHRlc3RfZGVsZXRpbmdfY2xpZW50X2tlZXBzX3Byb2plY3RzKHNlbGYsIHNl"
        "c3Npb24sIGNsaWVudCwgcHJvamVjdCk6CiAgICAgICAgIiIiCiAgICAgICAg2K3YsNmBINin2YTYudmF2YrZhCDZg9in"
        "2YYg2YrYrdiw2YEg2YXYtNin2LHZiti52Ycg2YjZgdmI2KfYqtmK2LHZh9inINmI2YXYudiv2KfYqtmH2Kcg2KjYtdmF"
        "2KogKGNhc2NhZGUpLgogICAgICAgINin2YTYotmGINmK2KjZgtmJINin2YTZhdi02LHZiNi5INmI2YrYtdio2K0g2KjZ"
        "hNinINi52YXZitmELgogICAgICAgICIiIgogICAgICAgIHNlc3Npb24uZGVsZXRlKGNsaWVudCkKICAgICAgICBzZXNz"
        "aW9uLmNvbW1pdCgpCiAgICAgICAgcCA9IHNlc3Npb24ucXVlcnkoZGIuUHJvamVjdCkuZmlyc3QoKQogICAgICAgIGFz"
        "c2VydCBwIGlzIG5vdCBOb25lCiAgICAgICAgYXNzZXJ0IHAuY2xpZW50X2lkIGlzIE5vbmUKICAgICAgICBhc3NlcnQg"
        "cC5jbGllbnRfbmFtZSA9PSAiIgoKICAgIGRlZiB0ZXN0X2RlbGV0aW5nX3Byb2plY3RfcmVtb3Zlc19lcXVpcG1lbnRf"
        "YW5kX2ludm9pY2VzKHNlbGYsIHNlc3Npb24sIHByb2plY3QpOgogICAgICAgIHNlc3Npb24uYWRkX2FsbChbCiAgICAg"
        "ICAgICAgIGRiLkVxdWlwbWVudChwcm9qZWN0X2lkPXByb2plY3QuaWQsIG5hbWU9Iti32YHYp9mK2KkiKSwKICAgICAg"
        "ICAgICAgZGIuSW52b2ljZShwcm9qZWN0X2lkPXByb2plY3QuaWQsIGFtb3VudD0xMDAwKSwKICAgICAgICBdKQogICAg"
        "ICAgIHNlc3Npb24uY29tbWl0KCkKICAgICAgICBzZXNzaW9uLmRlbGV0ZShwcm9qZWN0KQogICAgICAgIHNlc3Npb24u"
        "Y29tbWl0KCkKICAgICAgICBhc3NlcnQgc2Vzc2lvbi5xdWVyeShkYi5FcXVpcG1lbnQpLmNvdW50KCkgPT0gMAogICAg"
        "ICAgIGFzc2VydCBzZXNzaW9uLnF1ZXJ5KGRiLkludm9pY2UpLmNvdW50KCkgPT0gMAoKCmNsYXNzIFRlc3REYXNoYm9h"
        "cmRTdGF0czoKCiAgICBkZWYgdGVzdF9zdGF0c19pbmNsdWRlX2NvbnRyYWN0X2tleXMoc2VsZiwgc2Vzc2lvbik6CiAg"
        "ICAgICAgc3RhdHMgPSBkYi5kYXNoYm9hcmRfc3RhdHMoc2Vzc2lvbikKICAgICAgICBmb3Iga2V5IGluICgidG90YWxf"
        "Y29udHJhY3RzIiwgImFjdGl2ZV9jb250cmFjdHMiLCAiY29udHJhY3RzX3ZhbHVlIiwKICAgICAgICAgICAgICAgICAg"
        "ICAiY29udHJhY3RfYWxlcnRzIiwgImR1ZV92aXNpdHMiLCAiZXF1aXBtZW50X2FsZXJ0cyIsCiAgICAgICAgICAgICAg"
        "ICAgICAgInRvdGFsX2ludm9pY2VkIiwgInRvdGFsX3VucGFpZCIsICJvdmVyZHVlX2ludm9pY2VzIik6CiAgICAgICAg"
        "ICAgIGFzc2VydCBrZXkgaW4gc3RhdHMsIGYi2YXZgdiq2KfYrSDZhdmB2YLZiNivOiB7a2V5fSIKCiAgICBkZWYgdGVz"
        "dF9lbXB0eV9kYXRhYmFzZV9kb2VzX25vdF9jcmFzaChzZWxmLCBzZXNzaW9uKToKICAgICAgICAiIiLZgtin2LnYr9ip"
        "INmB2KfYsdi62Kkg2KrZhdin2YXZi9inIOKAlCDYo9mI2YQg2KrYtNi62YrZhCDZhNmE2KjYsdmG2KfZhdisLiIiIgog"
        "ICAgICAgIHN0YXRzID0gZGIuZGFzaGJvYXJkX3N0YXRzKHNlc3Npb24pCiAgICAgICAgYXNzZXJ0IHN0YXRzWyJ0b3Rh"
        "bF9wcm9qZWN0cyJdID09IDAKICAgICAgICBhc3NlcnQgc3RhdHNbInRvdGFsX2ludm9pY2VkIl0gPT0gMAogICAgICAg"
        "IGFzc2VydCBzdGF0c1siY29udHJhY3RzX3ZhbHVlIl0gPT0gMAoKICAgIGRlZiB0ZXN0X3ZhbHVlX2NvdW50c19hY3Rp"
        "dmVfY29udHJhY3RzX29ubHkoc2VsZiwgc2Vzc2lvbiwgY2xpZW50KToKICAgICAgICBzZXNzaW9uLmFkZF9hbGwoWwog"
        "ICAgICAgICAgICBkYi5Db250cmFjdChjbGllbnRfaWQ9Y2xpZW50LmlkLCBzdGF0dXM9IkFjdGl2ZSIsIHZhbHVlPTEw"
        "MDAwMCwKICAgICAgICAgICAgICAgICAgICAgICAgc3RhcnRfZGF0ZT1kYXRlLnRvZGF5KCkgLSB0aW1lZGVsdGEoZGF5"
        "cz0xMCksCiAgICAgICAgICAgICAgICAgICAgICAgIGVuZF9kYXRlPWRhdGUudG9kYXkoKSArIHRpbWVkZWx0YShkYXlz"
        "PTMwMCkpLAogICAgICAgICAgICBkYi5Db250cmFjdChjbGllbnRfaWQ9Y2xpZW50LmlkLCBzdGF0dXM9IkNhbmNlbGxl"
        "ZCIsIHZhbHVlPTUwMDAwMCwKICAgICAgICAgICAgICAgICAgICAgICAgc3RhcnRfZGF0ZT1kYXRlLnRvZGF5KCkgLSB0"
        "aW1lZGVsdGEoZGF5cz0xMCksCiAgICAgICAgICAgICAgICAgICAgICAgIGVuZF9kYXRlPWRhdGUudG9kYXkoKSArIHRp"
        "bWVkZWx0YShkYXlzPTMwMCkpLAogICAgICAgICAgICBkYi5Db250cmFjdChjbGllbnRfaWQ9Y2xpZW50LmlkLCBzdGF0"
        "dXM9IkFjdGl2ZSIsIHZhbHVlPTIwMDAwMCwKICAgICAgICAgICAgICAgICAgICAgICAgc3RhcnRfZGF0ZT1kYXRlKDIw"
        "MjUsIDEsIDEpLAogICAgICAgICAgICAgICAgICAgICAgICBlbmRfZGF0ZT1kYXRlKDIwMjUsIDEyLCAzMSkpLCAgIyDZ"
        "hdmG2KrZh9mNCiAgICAgICAgXSkKICAgICAgICBzZXNzaW9uLmNvbW1pdCgpCiAgICAgICAgc3RhdHMgPSBkYi5kYXNo"
        "Ym9hcmRfc3RhdHMoc2Vzc2lvbikKICAgICAgICBhc3NlcnQgc3RhdHNbInRvdGFsX2NvbnRyYWN0cyJdID09IDMKICAg"
        "ICAgICBhc3NlcnQgc3RhdHNbImFjdGl2ZV9jb250cmFjdHMiXSA9PSAxCiAgICAgICAgYXNzZXJ0IHN0YXRzWyJjb250"
        "cmFjdHNfdmFsdWUiXSA9PSAxMDAwMDAKCgpjbGFzcyBUZXN0U2VhcmNoOgoKICAgIGRlZiB0ZXN0X3NlYXJjaF9wcm9q"
        "ZWN0c19ieV90ZXh0X2FuZF9zdGF0dXMoc2VsZiwgc2Vzc2lvbiwgY2xpZW50KToKICAgICAgICBzZXNzaW9uLmFkZF9h"
        "bGwoWwogICAgICAgICAgICBkYi5Qcm9qZWN0KG5hbWU9Itio2LHYrCDYp9mE2YXZhdmE2YPYqSIsIGNsaWVudF9pZD1j"
        "bGllbnQuaWQsIHN0YXR1cz0iSW5zdGFsbCIpLAogICAgICAgICAgICBkYi5Qcm9qZWN0KG5hbWU9ItmF2KzZhdi5INin"
        "2YTZiNin2K3YqSIsIGNsaWVudF9pZD1jbGllbnQuaWQsIHN0YXR1cz0iRGVzaWduIiksCiAgICAgICAgXSkKICAgICAg"
        "ICBzZXNzaW9uLmNvbW1pdCgpCiAgICAgICAgYXNzZXJ0IGxlbihkYi5zZWFyY2hfcHJvamVjdHMoc2Vzc2lvbiwgdGV4"
        "dD0i2KfZhNmF2YXZhNmD2KkiKSkgPT0gMQogICAgICAgIGFzc2VydCBsZW4oZGIuc2VhcmNoX3Byb2plY3RzKHNlc3Np"
        "b24sIHN0YXR1cz0iRGVzaWduIikpID09IDEKICAgICAgICBhc3NlcnQgbGVuKGRiLnNlYXJjaF9wcm9qZWN0cyhzZXNz"
        "aW9uKSkgPT0gMgoKICAgIGRlZiB0ZXN0X3NwZWNpYWxfY2hhcmFjdGVyc19hcmVfZXNjYXBlZChzZWxmLCBzZXNzaW9u"
        "LCBjbGllbnQpOgogICAgICAgICIiIgogICAgICAgINin2YTYsdmF2LIgJSDZgdmKIExJS0Ug2YrYudmG2YogItij2Yog"
        "2LTZitihIi4g2KjZhNinINiq2YfYsdmK2Kgg2YrYudmK2K8g2KfZhNio2K3YqyDYudmGICIlIiDZg9mECiAgICAgICAg"
        "2KfZhNiz2KzZhNin2Kog2KjYr9mEINin2YTYs9is2YQg2KfZhNiw2Yog2YrYrdmI2YrZhyDZgdi52YTZi9inLgogICAg"
        "ICAgICIiIgogICAgICAgIHNlc3Npb24uYWRkX2FsbChbCiAgICAgICAgICAgIGRiLlByb2plY3QobmFtZT0i2YXYtNix"
        "2YjYuSAxMDAlINil2YbYrNin2LIiLCBjbGllbnRfaWQ9Y2xpZW50LmlkKSwKICAgICAgICAgICAgZGIuUHJvamVjdChu"
        "YW1lPSLZhdi02LHZiNi5INi52KfYr9mKIiwgY2xpZW50X2lkPWNsaWVudC5pZCksCiAgICAgICAgXSkKICAgICAgICBz"
        "ZXNzaW9uLmNvbW1pdCgpCiAgICAgICAgYXNzZXJ0IGxlbihkYi5zZWFyY2hfcHJvamVjdHMoc2Vzc2lvbiwgdGV4dD0i"
        "MTAwJSIpKSA9PSAxCg=="
    ),
    'tests/test_backup_and_migration.py': (
        "IiIiCtin2K7Yqtio2KfYsdin2Kog2KfZhNmG2LPYriDYp9mE2KfYrdiq2YrYp9i32Yog2YjYqtix2K3ZitmEINio2YbZ"
        "itipINmC2KfYudiv2Kkg2KfZhNio2YrYp9mG2KfYqi4KCtmH2LDZhyDYo9iu2LfYsSDYo9is2LLYp9ihINin2YTYqNix"
        "2YbYp9mF2Kw6INiu2YTZhCDZgdmKINin2YTZhtiz2K4gPSDZgdmC2K/Yp9mGINio2YrYp9mG2KfYqtiMINmI2K7ZhNmE"
        "INmB2Yog2KfZhNiq2LHYrdmK2YQgPQrYqNix2YbYp9mF2Kwg2YTYpyDZitmB2KrYrSDYudmE2Ykg2YLYp9i52K/YqSDY"
        "qNmK2KfZhtin2Kog2YLYr9mK2YXYqS4KIiIiCgppbXBvcnQgb3MKaW1wb3J0IHNxbGl0ZTMKCmltcG9ydCBhcHBsb2cK"
        "CgpkZWYgX21ha2VfZGIocGF0aCwgcm93cz0zKToKICAgIGNvbm4gPSBzcWxpdGUzLmNvbm5lY3QocGF0aCkKICAgIGNv"
        "bm4uZXhlY3V0ZSgiQ1JFQVRFIFRBQkxFIGNsaWVudHMgKGlkIElOVEVHRVIgUFJJTUFSWSBLRVksIG5hbWUgVEVYVCki"
        "KQogICAgZm9yIGkgaW4gcmFuZ2Uocm93cyk6CiAgICAgICAgY29ubi5leGVjdXRlKCJJTlNFUlQgSU5UTyBjbGllbnRz"
        "IChuYW1lKSBWQUxVRVMgKD8pIiwgKGYi2LnZhdmK2YQge2l9IiwpKQogICAgY29ubi5jb21taXQoKQogICAgY29ubi5j"
        "bG9zZSgpCgoKY2xhc3MgVGVzdEJhY2t1cDoKCiAgICBkZWYgdGVzdF9jcmVhdGVzX3ZlcmlmaWVkX2JhY2t1cChzZWxm"
        "LCB0bXBfcGF0aCk6CiAgICAgICAgZGIgPSB0bXBfcGF0aCAvICJkYi5zcWxpdGUzIgogICAgICAgIGJhY2t1cHMgPSB0"
        "bXBfcGF0aCAvICJiYWNrdXBzIgogICAgICAgIF9tYWtlX2RiKHN0cihkYikpCgogICAgICAgIG9rLCBkZXN0ID0gYXBw"
        "bG9nLmNyZWF0ZV9iYWNrdXAoc3RyKGRiKSwgc3RyKGJhY2t1cHMpKQogICAgICAgIGFzc2VydCBvayBpcyBUcnVlCiAg"
        "ICAgICAgYXNzZXJ0IG9zLnBhdGguZXhpc3RzKGRlc3QpCiAgICAgICAgYXNzZXJ0IGFwcGxvZy52ZXJpZnlfYmFja3Vw"
        "KGRlc3QpIGlzIFRydWUKCiAgICBkZWYgdGVzdF9iYWNrdXBfcHJlc2VydmVzX2RhdGEoc2VsZiwgdG1wX3BhdGgpOgog"
        "ICAgICAgIGRiID0gdG1wX3BhdGggLyAiZGIuc3FsaXRlMyIKICAgICAgICBfbWFrZV9kYihzdHIoZGIpLCByb3dzPTUp"
        "CiAgICAgICAgb2ssIGRlc3QgPSBhcHBsb2cuY3JlYXRlX2JhY2t1cChzdHIoZGIpLCBzdHIodG1wX3BhdGggLyAiYiIp"
        "KQoKICAgICAgICBjb25uID0gc3FsaXRlMy5jb25uZWN0KGRlc3QpCiAgICAgICAgY291bnQgPSBjb25uLmV4ZWN1dGUo"
        "IlNFTEVDVCBDT1VOVCgqKSBGUk9NIGNsaWVudHMiKS5mZXRjaG9uZSgpWzBdCiAgICAgICAgY29ubi5jbG9zZSgpCiAg"
        "ICAgICAgYXNzZXJ0IGNvdW50ID09IDUKCiAgICBkZWYgdGVzdF90d29fYmFja3Vwc19zYW1lX3NlY29uZF9kb19ub3Rf"
        "b3ZlcndyaXRlKHNlbGYsIHRtcF9wYXRoKToKICAgICAgICAiIiIKICAgICAgICDYp9mE2K7ZhNmEINin2YTYo9i12YTZ"
        "ijog2KfZhNin2LPZhSDYqNin2YTYqtin2LHZitiuINmB2YLYt9iMINmB2YbYs9iu2Kkg2KvYp9mG2YrYqSDZgdmKINin"
        "2YTZitmI2YUg2YbZgdiz2Ycg2KrZhdit2YgKICAgICAgICDYp9mE2KPZiNmE2YkuINmI2K3YqtmJINio2LnYryDYpdi2"
        "2KfZgdipINin2YTZiNmC2Kog2KjYp9mE2KvYp9mG2YrYqSDYqNmC2Yog2KfZhNiq2LXYp9iv2YUg2YXZhdmD2YbZi9in"
        "INit2YrZhiDYqtmC2LkKICAgICAgICDZhtiz2K7Yqtin2YYg2YHZiiDYp9mE2KvYp9mG2YrYqSDZhtmB2LPZh9inICjY"
        "p9mE2YbYs9iu2Kkg2KfZhNiq2YTZgtin2KbZitipINir2YUg2LbYuti32Kkg2YrYr9mI2YrYqSDZgdmI2LHZitipKS4K"
        "ICAgICAgICAiIiIKICAgICAgICBkYiA9IHRtcF9wYXRoIC8gImRiLnNxbGl0ZTMiCiAgICAgICAgYmFja3VwcyA9IHRt"
        "cF9wYXRoIC8gImJhY2t1cHMiCiAgICAgICAgX21ha2VfZGIoc3RyKGRiKSkKCiAgICAgICAgcGF0aHMgPSBbYXBwbG9n"
        "LmNyZWF0ZV9iYWNrdXAoc3RyKGRiKSwgc3RyKGJhY2t1cHMpKVsxXSBmb3IgXyBpbiByYW5nZSg1KV0KCiAgICAgICAg"
        "YXNzZXJ0IGxlbihzZXQocGF0aHMpKSA9PSA1LCAi2KPYs9mF2KfYoSDZhdiq2YPYsdmR2LHYqSDigJQg2YbYs9iu2Kkg"
        "2YXYrdiqINij2K7YsdmJIgogICAgICAgIGFzc2VydCBsZW4ob3MubGlzdGRpcihiYWNrdXBzKSkgPT0gNQoKICAgIGRl"
        "ZiB0ZXN0X3BydW5lX2tlZXBzX25ld2VzdF9vbmx5KHNlbGYsIHRtcF9wYXRoKToKICAgICAgICBkYiA9IHRtcF9wYXRo"
        "IC8gImRiLnNxbGl0ZTMiCiAgICAgICAgYmFja3VwcyA9IHRtcF9wYXRoIC8gImJhY2t1cHMiCiAgICAgICAgX21ha2Vf"
        "ZGIoc3RyKGRiKSkKCiAgICAgICAgZm9yIF8gaW4gcmFuZ2UoNik6CiAgICAgICAgICAgIGFwcGxvZy5jcmVhdGVfYmFj"
        "a3VwKHN0cihkYiksIHN0cihiYWNrdXBzKSwga2VlcD0zKQoKICAgICAgICBhc3NlcnQgbGVuKG9zLmxpc3RkaXIoYmFj"
        "a3VwcykpID09IDMKCiAgICBkZWYgdGVzdF9taXNzaW5nX2RhdGFiYXNlX3JlcG9ydHNfZmFpbHVyZShzZWxmLCB0bXBf"
        "cGF0aCk6CiAgICAgICAgb2ssIG1zZyA9IGFwcGxvZy5jcmVhdGVfYmFja3VwKHN0cih0bXBfcGF0aCAvICLZhNinLdmK"
        "2YjYrNivLnNxbGl0ZTMiKSwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgc3RyKHRtcF9wYXRo"
        "IC8gImIiKSkKICAgICAgICBhc3NlcnQgb2sgaXMgRmFsc2UKICAgICAgICBhc3NlcnQgaXNpbnN0YW5jZShtc2csIHN0"
        "cikgYW5kIG1zZwoKICAgIGRlZiB0ZXN0X2NvcnJ1cHRfZmlsZV9mYWlsc192ZXJpZmljYXRpb24oc2VsZiwgdG1wX3Bh"
        "dGgpOgogICAgICAgIGJhZCA9IHRtcF9wYXRoIC8gImJhZC5zcWxpdGUzIgogICAgICAgIGJhZC53cml0ZV9ieXRlcyhi"
        "Im5vdCBhIGRhdGFiYXNlIikKICAgICAgICBhc3NlcnQgYXBwbG9nLnZlcmlmeV9iYWNrdXAoc3RyKGJhZCkpIGlzIEZh"
        "bHNlCgogICAgZGVmIHRlc3RfYXV0b19iYWNrdXBfcnVuc19vbmNlX3Blcl9kYXkoc2VsZiwgdG1wX3BhdGgpOgogICAg"
        "ICAgIGRiID0gdG1wX3BhdGggLyAiZGIuc3FsaXRlMyIKICAgICAgICBiYWNrdXBzID0gdG1wX3BhdGggLyAiYmFja3Vw"
        "cyIKICAgICAgICBfbWFrZV9kYihzdHIoZGIpKQoKICAgICAgICBmaXJzdCA9IGFwcGxvZy5hdXRvX2JhY2t1cF9vbl9z"
        "dGFydChzdHIoZGIpLCBzdHIoYmFja3VwcykpCiAgICAgICAgc2Vjb25kID0gYXBwbG9nLmF1dG9fYmFja3VwX29uX3N0"
        "YXJ0KHN0cihkYiksIHN0cihiYWNrdXBzKSkKCiAgICAgICAgYXNzZXJ0IGZpcnN0IGlzIG5vdCBOb25lCiAgICAgICAg"
        "YXNzZXJ0IHNlY29uZCBpcyBOb25lLCAi2KPZhti02KMg2YbYs9iu2Kkg2KrZhNmC2KfYptmK2Kkg2KvYp9mG2YrYqSDZ"
        "gdmKINin2YTZitmI2YUg2YbZgdiz2YciCgoKY2xhc3MgVGVzdE1pZ3JhdGlvbjoKICAgICIiIgogICAgY3JlYXRlX2Fs"
        "bCgpINmK2YbYtNimINin2YTYrNiv2KfZiNmEINin2YTZhtin2YLYtdipINmB2YLYtyDZiNmE2Kcg2YrYttmK2YEg2LnZ"
        "hdmI2K/Zi9inINil2YTZiSDYrNiv2YjZhCDZgtin2KbZhS4KICAgINio2K/ZiNmGINin2YTYqtix2K3ZitmEINmK2YHY"
        "tNmEINin2YTYqNix2YbYp9mF2Kwg2LnZhNmJINmC2KfYudiv2Kkg2KjZitin2YbYp9iqINin2YTZhdiz2KrYrtiv2YUg"
        "2KfZhNit2KfZhNmK2Kkg2KjYrti32KMKICAgICJubyBzdWNoIGNvbHVtbjogaW52b2ljZXMuY29udHJhY3RfaWQiLgog"
        "ICAgIiIiCgogICAgZGVmIHRlc3RfYWRkc19taXNzaW5nX2NvbHVtbl90b19leGlzdGluZ190YWJsZShzZWxmLCB0bXBf"
        "cGF0aCwgbW9ua2V5cGF0Y2gpOgogICAgICAgIGltcG9ydCBpbXBvcnRsaWIKICAgICAgICBpbXBvcnQgc3FsYWxjaGVt"
        "eQoKICAgICAgICBkYl9wYXRoID0gdG1wX3BhdGggLyAib2xkLnNxbGl0ZTMiCiAgICAgICAgY29ubiA9IHNxbGl0ZTMu"
        "Y29ubmVjdChzdHIoZGJfcGF0aCkpCiAgICAgICAgY29ubi5leGVjdXRlc2NyaXB0KCIiIgogICAgICAgICAgICBDUkVB"
        "VEUgVEFCTEUgY2xpZW50cyAoaWQgSU5URUdFUiBQUklNQVJZIEtFWSwgbmFtZSBURVhUKTsKICAgICAgICAgICAgQ1JF"
        "QVRFIFRBQkxFIHByb2plY3RzIChpZCBJTlRFR0VSIFBSSU1BUlkgS0VZLCBuYW1lIFRFWFQsCiAgICAgICAgICAgICAg"
        "ICAgICAgICAgICAgICAgICAgICAgY2xpZW50X2lkIElOVEVHRVIpOwogICAgICAgICAgICBDUkVBVEUgVEFCTEUgaW52"
        "b2ljZXMgKGlkIElOVEVHRVIgUFJJTUFSWSBLRVksIHByb2plY3RfaWQgSU5URUdFUiwKICAgICAgICAgICAgICAgICAg"
        "ICAgICAgICAgICAgICAgICBpbnZvaWNlX251bWJlciBURVhULCBhbW91bnQgRkxPQVQsCiAgICAgICAgICAgICAgICAg"
        "ICAgICAgICAgICAgICAgICAgc3RhdHVzIFRFWFQpOwogICAgICAgICAgICBJTlNFUlQgSU5UTyBjbGllbnRzIChuYW1l"
        "KSBWQUxVRVMgKCfYudmF2YrZhCDZgtiv2YrZhScpOwogICAgICAgICAgICBJTlNFUlQgSU5UTyBwcm9qZWN0cyAobmFt"
        "ZSwgY2xpZW50X2lkKSBWQUxVRVMgKCfZhdi02LHZiNi5INmC2K/ZitmFJywgMSk7CiAgICAgICAgICAgIElOU0VSVCBJ"
        "TlRPIGludm9pY2VzIChwcm9qZWN0X2lkLCBpbnZvaWNlX251bWJlciwgYW1vdW50LCBzdGF0dXMpCiAgICAgICAgICAg"
        "ICAgICBWQUxVRVMgKDEsICdJTlYtT0xEJywgNTAwMCwgJ1VucGFpZCcpOwogICAgICAgICIiIikKICAgICAgICBjb25u"
        "LmNvbW1pdCgpCiAgICAgICAgY29ubi5jbG9zZSgpCgogICAgICAgIGJlZm9yZSA9IFtyWzFdIGZvciByIGluIHNxbGl0"
        "ZTMuY29ubmVjdChzdHIoZGJfcGF0aCkpCiAgICAgICAgICAgICAgICAgIC5leGVjdXRlKCJQUkFHTUEgdGFibGVfaW5m"
        "byhpbnZvaWNlcykiKV0KICAgICAgICBhc3NlcnQgImNvbnRyYWN0X2lkIiBub3QgaW4gYmVmb3JlCgogICAgICAgIGlt"
        "cG9ydCBkYXRhYmFzZSBhcyBkYgogICAgICAgIGVuZ2luZSA9IHNxbGFsY2hlbXkuY3JlYXRlX2VuZ2luZShmInNxbGl0"
        "ZTovLy97ZGJfcGF0aH0iLCBmdXR1cmU9VHJ1ZSkKICAgICAgICBtb25rZXlwYXRjaC5zZXRhdHRyKGRiLCAiZW5naW5l"
        "IiwgZW5naW5lKQogICAgICAgIGRiLl9taWdyYXRlX2FkZF9jb2x1bW5zKCkKCiAgICAgICAgYWZ0ZXIgPSBbclsxXSBm"
        "b3IgciBpbiBzcWxpdGUzLmNvbm5lY3Qoc3RyKGRiX3BhdGgpKQogICAgICAgICAgICAgICAgIC5leGVjdXRlKCJQUkFH"
        "TUEgdGFibGVfaW5mbyhpbnZvaWNlcykiKV0KICAgICAgICBhc3NlcnQgImNvbnRyYWN0X2lkIiBpbiBhZnRlcgoKICAg"
        "ICAgICAjINin2YTYqNmK2KfZhtin2Kog2KfZhNmC2K/ZitmF2Kkg2LPZhNmK2YXYqQogICAgICAgIGNvbm4gPSBzcWxp"
        "dGUzLmNvbm5lY3Qoc3RyKGRiX3BhdGgpKQogICAgICAgIGFzc2VydCBjb25uLmV4ZWN1dGUoIlNFTEVDVCBDT1VOVCgq"
        "KSBGUk9NIGludm9pY2VzIikuZmV0Y2hvbmUoKVswXSA9PSAxCiAgICAgICAgYXNzZXJ0IGNvbm4uZXhlY3V0ZSgKICAg"
        "ICAgICAgICAgIlNFTEVDVCBpbnZvaWNlX251bWJlciBGUk9NIGludm9pY2VzIikuZmV0Y2hvbmUoKVswXSA9PSAiSU5W"
        "LU9MRCIKICAgICAgICBjb25uLmNsb3NlKCkKCiAgICBkZWYgdGVzdF9taWdyYXRpb25faXNfaWRlbXBvdGVudChzZWxm"
        "LCB0bXBfcGF0aCwgbW9ua2V5cGF0Y2gpOgogICAgICAgICIiItiq2LTYutmK2YTZhyDZhdix2KrZitmGINmK2KzYqCDY"
        "o9mE2Kcg2YrZgdi02YQgKNmK2K3Yr9irINi52YbYryDZg9mEINil2YLZhNin2LkpLiIiIgogICAgICAgIGltcG9ydCBz"
        "cWxhbGNoZW15CiAgICAgICAgaW1wb3J0IGRhdGFiYXNlIGFzIGRiCgogICAgICAgIGRiX3BhdGggPSB0bXBfcGF0aCAv"
        "ICJ4LnNxbGl0ZTMiCiAgICAgICAgY29ubiA9IHNxbGl0ZTMuY29ubmVjdChzdHIoZGJfcGF0aCkpCiAgICAgICAgY29u"
        "bi5leGVjdXRlKCJDUkVBVEUgVEFCTEUgaW52b2ljZXMgKGlkIElOVEVHRVIgUFJJTUFSWSBLRVkpIikKICAgICAgICBj"
        "b25uLmNvbW1pdCgpCiAgICAgICAgY29ubi5jbG9zZSgpCgogICAgICAgIGVuZ2luZSA9IHNxbGFsY2hlbXkuY3JlYXRl"
        "X2VuZ2luZShmInNxbGl0ZTovLy97ZGJfcGF0aH0iLCBmdXR1cmU9VHJ1ZSkKICAgICAgICBtb25rZXlwYXRjaC5zZXRh"
        "dHRyKGRiLCAiZW5naW5lIiwgZW5naW5lKQogICAgICAgIGRiLl9taWdyYXRlX2FkZF9jb2x1bW5zKCkKICAgICAgICBk"
        "Yi5fbWlncmF0ZV9hZGRfY29sdW1ucygpICAjINmE2Kcg2YrYrNioINij2YYg2YrYsdmF2Yog2KfYs9iq2KvZhtin2KEK"
        "CgpjbGFzcyBUZXN0VmVyc2lvbjoKCiAgICBkZWYgdGVzdF92ZXJzaW9uX2lzX2RlZmluZWQoc2VsZik6CiAgICAgICAg"
        "YXNzZXJ0IGFwcGxvZy5fX3ZlcnNpb25fXwogICAgICAgIGFzc2VydCBhcHBsb2cuX192ZXJzaW9uX18uY291bnQoIi4i"
        "KSA9PSAyCg=="
    ),
    'pytest.ini': (
        "W3B5dGVzdF0KdGVzdHBhdGhzID0gdGVzdHMKcHl0aG9uX2ZpbGVzID0gdGVzdF8qLnB5CnB5dGhvbl9jbGFzc2VzID0g"
        "VGVzdCoKcHl0aG9uX2Z1bmN0aW9ucyA9IHRlc3RfKgphZGRvcHRzID0gLXEK"
    ),
    'run_tests.bat': (
        "QGVjaG8gb2ZmDQpSRU0g2KrYtNi62YrZhCDYp9iu2KrYqNin2LHYp9iqIEZpcmVFbmdpbmVlckFJIC0g2KfZhtmC2LEg"
        "2YXYsdiq2YrZhiDYudmE2Ykg2YfYsNinINin2YTZhdmE2YENCmNkIC9kICIlfmRwMCINCmVjaG8uDQplY2hvID09PSDY"
        "p9iu2KrYqNin2LHYp9iqIEZpcmVFbmdpbmVlckFJID09PQ0KZWNoby4NCnB5dGhvbiAtbSBweXRlc3QgdGVzdHMgLXYN"
        "CmVjaG8uDQpwYXVzZQ0K"
    ),
    'requirements-dev.txt': (
        "cHl0ZXN0Pj04LjAK"
    ),
}

# ---- إصلاح is_overdue: "and" تعيد المعامل الزائف نفسه، فكانت تعيد None ----
PATCHES = [
    (
        '        return self.status != "Paid" and self.due_date '
        'and self.due_date < date.today()',
        '        # bool() مقصودة: تعبير "and" يعيد المعامل الزائف نفسه، فكانت\n'
        '        # الخاصية تعيد None (لا False) حين لا يوجد تاريخ استحقاق —\n'
        '        # فيظهر "None" في تصدير CSV وتفشل أي مقارنة صارمة (is False).\n'
        '        return bool(self.status != "Paid" and self.due_date\n'
        '                    and self.due_date < date.today())',
    ),
    (
        '        return (self.status == "Scheduled" and self.visit_date\n'
        '                and self.visit_date < date.today())',
        '        return bool(self.status == "Scheduled" and self.visit_date\n'
        '                    and self.visit_date < date.today())',
    ),
]


def main():
    here = os.path.dirname(os.path.abspath(__file__))

    if not os.path.exists(os.path.join(here, "database.py")):
        print("\n[خطأ] لا يوجد database.py في هذا المجلد.")
        print("      ضع install_tests.py داخل C:\\Projects\\FireEngineerAI وأعد التشغيل.")
        return 1

    print("\n=== تركيب اختبارات FireEngineerAI ===\n")

    os.makedirs(os.path.join(here, "tests"), exist_ok=True)
    for name, blob in FILES.items():
        dest = os.path.join(here, name.replace("/", os.sep))
        with open(dest, "wb") as fh:
            fh.write(base64.b64decode(blob))
        print(f"  [ملف]   {name}  ({os.path.getsize(dest)} بايت)")

    # --- إصلاح database.py ---
    db_path = os.path.join(here, "database.py")
    src = open(db_path, encoding="utf-8").read()

    if "bool(self.status" in src:
        print("\n  [تخطٍّ]  database.py مُصلَح مسبقًا.")
    else:
        applied = 0
        for old, new in PATCHES:
            if old in src:
                src = src.replace(old, new, 1)
                applied += 1

        if applied == 2:
            shutil.copy2(db_path, db_path + ".bak")
            with open(db_path, "w", encoding="utf-8") as fh:
                fh.write(src)
            print("\n  [إصلاح] database.py — is_overdue تعيد False بدل None")
            print("          (نسخة احتياطية: database.py.bak)")
        else:
            print(f"\n  [تحذير] لم يُطبَّق الإصلاح ({applied}/2 موضع).")
            print("          الاختبارات ستعمل، لكن اختبار is_overdue سيسقط.")

    # --- تنظيف الكاش القديم ---
    for cache in (os.path.join(here, "__pycache__"),
                  os.path.join(here, "tests", "__pycache__")):
        if os.path.isdir(cache):
            shutil.rmtree(cache, ignore_errors=True)
            print(f"  [حذف]   {os.path.basename(os.path.dirname(cache))}\\__pycache__")

    print("\n=== تم. شغّل الآن: ===\n")
    print("    python -m pytest tests -v\n")
    print("أو انقر مرتين على run_tests.bat")
    print("النتيجة المتوقعة: 53 passed\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
